// Generated by CoffeeScript 1.12.6
(function() {
  Session.set('user', null);

  Session.set('serverURL', null);

  Session.set('graphName', null);

  Session.set('scriptName', null);

  Session.set('scriptResult', null);

  Session.set('graphRenderingStatus', 'Run script first');

  Session.set('graphToShow', {
    nodes: [],
    edges: []
  });

  Session.set('retrieveVerticesAsNeeded', true);

  Session.set('drawCurvedEdges', false);

  Session.set('drawEdgeLabels', true);

  Session.set('drawEdges', true);

  Session.set('examples-userID', 'examples@tinkertools.com');

  Session.set('admin-userID', 'admin@tinkertools.com');

  Session.set('queryTime', 'N/A');

  Session.set('elapsedTime', 'N/A');

  Session.set('runStatus', 'Ready');

  Session.set('githubURL', 'https://github.com/ssadams11/tinkertoolsOSS');

  Session.set('githubIssuesURL', 'https://github.com/ssadams11/tinkertoolsOSS/issues');

  Session.set('graphFoundInResults', false);

  Session.set('drawButtonPressed', false);

  Session.set('elapsedRenderTime', '');

  Session.set('usingWebSockets', false);

  Meteor.subscribe('scripts');

  Meteor.subscribe('userStatus');

  Tracker.autorun(function() {
    var userID;
    if (Meteor.user()) {
      userID = Meteor.user().emails[0].address;
      return Session.set('userID', userID);
    } else {
      return Session.set('userID', null);

      /*
      Meteor._reload.onMigrate = ->
        return [false]
       */
    }
  });

}).call(this);

//# sourceMappingURL=app.js.map
