// Generated by CoffeeScript 1.12.6
(function() {
  Template.BluemixGraphButtons.rendered = function() {
    return $(".graph-addBluemix").click(function() {
      return bootbox.dialog({
        title: "Provide your Bluemix Graph Service Credentials here:",
        message: Blaze.toHTML(Template.BluemixGraphServiceCreds),
        buttons: {
          success: {
            label: "Add",
            className: "btn-success",
            callback: function() {
              var api, newGraphName, pass, user;
              newGraphName = $('#newGraphName').val();
              api = $('#bluemixGraphAPI').val();
              user = $('#bluemixUsername').val();
              pass = $('#bluemixPassword').val();
              if (newGraphName) {
                Session.set('graphNames', []);
                Scripts.insert({
                  userID: Session.get('userID'),
                  serverURL: Session.get('serverURL'),
                  graphName: newGraphName,
                  bluemixUsername: user,
                  bluemixAPI: api,
                  bluemixPassword: pass
                });
                Session.set('graphName', newGraphName);
                window.BluemixUsername = user;
                window.BluemixAPI = api;
                window.BluemixPassword = pass;
                return setTimeout(function() {
                  return document.getElementById('graphSelector').value = newGraphName;
                }, 500);
              }
            }
          }
        }
      });
    });
  };

}).call(this);

//# sourceMappingURL=BluemixGraphButtons.js.map
