// Generated by CoffeeScript 1.12.6
(function() {
  Template.Help.rendered = function() {
    $(".goto-gitlab").click(function() {
      return open(Session.get('gitLabURL'));
    });
    return $(".goto-gitlab-issues").click(function() {
      return open(Session.get('gitLabIssuesURL'));
    });
  };

}).call(this);

//# sourceMappingURL=Help.js.map
