// Generated by CoffeeScript 1.12.6
(function() {
  Template.Home.rendered = function() {
    var wsUri;
    Session.set('useLabelPrefix', true);
    Session.set('keyForNodeLabel', "null");
    wsUri = Session.get("serverURL");
    window.wsConnect = function(wsUri) {
      console.log("connecting to ", wsUri);
      document.getElementById('ws-status').innerHTML = "<p style='font-size:16px; background-color: yellow; color: black;'>trying Websocket connection...</p>";
      window.socketToJanus = new WebSocket(wsUri + "/gremlin");
      window.socketToJanus.onmessage = function(msg) {
        var data, json;
        data = msg.data;
        json = JSON.parse(data);
        return window.dispatcher(json);
      };
      window.socketToJanus.onopen = function() {
        document.getElementById('ws-status').innerHTML = "<p style='font-size:16px; background-color: white; color: green;'>connected via Websocket</p>";
        return console.log("connected to", wsUri);
      };
      return window.socketToJanus.onclose = function() {
        document.getElementById('ws-status').innerHTML = "<p style='font-size:16px; background-color: white; color: red;'>not connected</p>";
        console.log("closed to", wsUri);
        return setTimeout(window.wsConnect, 3000);
      };
    };
    Session.set("usingWebSockets", true);
    try {
      return window.wsConnect(Session.get("serverURL"));
    } catch (error) {
      Session.set("usingWebSockets", false);
      return document.getElementById('ws-status').innerHTML = "<p style='font-size:16px; background-color: white; color: black;'>Connected via HTTP</p>";
    }
  };

  Meteor.Spinner.options = {
    lines: 13,
    length: 10,
    width: 5,
    radius: 15,
    corners: 0.7,
    rotate: 0,
    direction: 1,
    color: '#fff',
    speed: 1,
    trail: 60,
    shadow: true,
    hwaccel: false,
    className: 'spinner',
    zIndex: 2e9,
    top: 'auto',
    left: 'auto'
  };

  Template.Home.helpers({
    isAdmin: function() {
      return (Session.get('userID')) === (Session.get('admin-userID'));
    },
    notAdmin: function() {
      return (Session.get('userID')) !== (Session.get('admin-userID'));
    },
    userLoggedIn: function() {
      return (Session.get('userID')) !== null;
    },
    graphSelected: function() {
      return (Session.get('graphName')) !== null;
    },
    scriptSelected: function() {
      return (Session.get('scriptName')) !== null;
    },
    scriptResult: function() {
      return Session.get('showJSONResult');
    },
    graphToShow: function() {
      return Session.get('graphFoundInResults');
    },
    drawingGraph: function() {
      return Session.get('drawGraphResult');
    }
  });

}).call(this);

//# sourceMappingURL=Home.js.map
