// Generated by CoffeeScript 1.12.6
(function() {
  Template.MigrationSplash.rendered = function() {
    return $(".use-server-anyway").click(function() {
      alert();
      return open('/Open');
    });
  };

}).call(this);

//# sourceMappingURL=MigrationSplash.js.map
