// Generated by CoffeeScript 1.12.6
(function() {
  Template.OtherScriptButtons.rendered = function() {
    $(".script-delete").click(function() {
      var deadName;
      deadName = $("#scriptSelector").val();
      if (deadName) {
        Session.set('scriptName', null);
        window.ScriptEditor.setValue('Select a script from above or add a named script first using the [+Add] button.');
        return Meteor.call('removeScript', Session.get('userID'), Session.get('serverURL'), Session.get('graphName'), deadName);
      }
    });
    $(".script-save").click(function() {
      var code, graphName, modifier, record, saveName, scriptName, selector, serverURL, userID;
      saveName = $("#scriptSelector").val();
      userID = Session.get('userID');
      serverURL = Session.get('serverURL');
      graphName = Session.get('graphName');
      scriptName = Session.get('scriptName');
      code = window.ScriptEditor.getValue();
      record = Scripts.findOne({
        userID: userID,
        serverURL: serverURL,
        graphName: graphName,
        scriptName: scriptName
      });
      if (!record) {
        return Scripts.insert({
          userID: userID,
          serverURL: serverURL,
          graphName: graphName,
          scriptName: saveName,
          scriptCode: code,
          scriptResult: {}
        });
      } else {
        if (saveName !== '') {
          selector = {
            userID: Session.get('userID'),
            serverURL: Session.get('serverURL'),
            graphName: Session.get('graphName'),
            scriptName: saveName
          };
          modifier = {
            $set: {
              scriptResult: {},
              scriptCode: code
            }
          };
          return Meteor.call('updateScript', selector, modifier);
        }
      }
    });
    return $(".script-duplicate").click(function() {
      var oldName, suggestion;
      oldName = $("#scriptSelector").val();
      suggestion = "<copy of> " + oldName;
      return bootbox.prompt({
        title: "Enter the name for the new script",
        value: suggestion,
        callback: function(newName) {
          if (newName) {
            Scripts.insert({
              userID: Session.get('userID'),
              serverURL: Session.get('serverURL'),
              graphName: Session.get('graphName'),
              scriptName: newName,
              scriptCode: window.ScriptEditor.getValue(),
              scriptResult: {},
              bluemixUsername: window.BluemixUsername,
              bluemixAPI: window.BluemixAPI,
              bluemixPassword: window.BluemixPassword
            });
            Session.set('scriptName', newName);
            return setTimeout(function() {
              return document.getElementById('scriptSelector').value = newName;
            }, 500);
          }
        }
      });
    });
  };

  Template.OtherScriptButtons.helpers;

}).call(this);

//# sourceMappingURL=OtherScriptButtons.js.map
