// Generated by CoffeeScript 1.12.6
(function() {
  Template.OtherServerButtons.rendered = function() {
    return $(".server-deleteURL").click(function() {
      return bootbox.confirm({
        message: "Are you sure you want to delete all your scripts for all graphs on " + Session.get('serverURL') + "?",
        callback: function(answer) {
          if (answer) {
            Meteor.call('removeURL', Session.get('userID'), Session.get('serverURL'));
            Session.set('serverURL', null);
            return setTimeout(function() {
              return document.getElementById('serverSelector').value = '';
            }, 500);
          }
        }
      });
    });
  };

  Template.OtherServerButtons.helpers({
    notTP3: function() {
      return (Session.get('tinkerPopVersion')) !== '3';
    },
    notBluemix: function() {
      return (Session.get('serverURL')) !== window.BluemixGraphService;
    }
  });

}).call(this);

//# sourceMappingURL=OtherServerButtons.js.map
