// Generated by CoffeeScript 1.12.6
(function() {
  Template.ReturnHostURL.rendered = function() {};

  Template.ReturnHostURL.helpers({
    hostURL: function() {
      return Session.get('hostURL');
    }
  });

}).call(this);

//# sourceMappingURL=ReturnHostURL.js.map
