// Generated by CoffeeScript 1.12.6
(function() {
  Template.ScriptButtons.rendered = function() {
    $(".script-add").click(function() {
      return bootbox.prompt("Enter the name for the new script", function(newName) {
        if (newName) {
          if ((Session.get('serverURL')) === window.BluemixGraphService) {
            Scripts.insert({
              userID: Session.get('userID'),
              serverURL: Session.get('serverURL'),
              graphName: Session.get('graphName'),
              scriptName: newName,
              scriptCode: "g.V().count()",
              scriptResult: {},
              bluemixUsername: window.BluemixUsername,
              bluemixAPI: window.BluemixAPI,
              bluemixPassword: window.BluemixPassword
            });
          } else {
            Scripts.insert({
              userID: Session.get('userID'),
              serverURL: Session.get('serverURL'),
              graphName: Session.get('graphName'),
              scriptName: newName,
              scriptCode: "g.V().count()",
              scriptResult: {}
            });
          }
          Session.set('scriptName', newName);
          window.ScriptEditor.setValue('g.V().count()');
          return setTimeout(function() {
            return document.getElementById('scriptSelector').value = newName;
          }, 500);
        }
      });
    });
    $(".gremlin-docs").click(function() {
      return open("http://gremlindocs.com/");
    });
    $(".groovy-docs").click(function() {
      return open("http://www.groovy-lang.org/groovy-dev-kit.html");
    });
    $(".tinkerpop-docs").click(function() {
      return open("http://tinkerpop.apache.org/docs/3.1.1-incubating/reference/");
    });
    $(".getting-started").click(function() {
      return open("http://tinkerpop.apache.org/docs/3.2.0-incubating/tutorials/getting-started/");
    });
    return $(".sql2gremlin").click(function() {
      return open("http://sql2gremlin.com/");
    });
  };

  Template.ScriptButtons.helpers({
    scriptSelected: function() {
      return (Session.get('scriptName')) !== null;
    },
    isTinkerPopVersion3: function() {
      return "3" === Session.get('tinkerPopVersion');
    },
    isTinkerPopVersion2: function() {
      return "2" === Session.get('tinkerPopVersion');
    }
  });

}).call(this);

//# sourceMappingURL=ScriptButtons.js.map
