// Generated by CoffeeScript 1.12.6
(function() {
  var discoverTinkerPopVersionAt;

  Template.ServerButtons.rendered = function() {
    return $(".server-addURL").click(function() {
      return bootbox.prompt({
        title: "Enter the URL for a graph server",
        value: 'http://graph.server.domain.name:8182',
        callback: function(newURL) {
          if (newURL) {
            Session.set('graphNames', []);
            Session.set('tinkerPopVersion', void 0);
            return discoverTinkerPopVersionAt(newURL, function(dat) {
              var tpVersion;
              tpVersion = dat[1];
              if (tpVersion === '0') {
                return alert('No Tinkerpop-compliant server at ' + newURL);
              } else {
                Scripts.insert({
                  userID: Session.get('userID'),
                  serverURL: newURL,
                  tinkerPopVersion: tpVersion
                });
                Session.set('serverURL', newURL);
                Session.set('tinkerPopVersion', tpVersion);
                return setTimeout(function() {
                  document.getElementById('serverSelector').value = newURL;
                  return $("#serverSelector").onchange();
                }, 500);
              }
            });
          }
        }
      });
    });
  };

  Template.ServerButtons.helpers({
    serverSelected: function() {
      return (Session.get('serverURL')) !== null;
    }
  });

  discoverTinkerPopVersionAt = function(url, callback) {
    return callback([0, 3]);
  };

}).call(this);

//# sourceMappingURL=ServerButtons.js.map
